In [2]:
import pandas as pd

In [8]:
data = pd.read_csv('check_EGFR.csv')
data.head()

,Sample ID,Patient ID,Diagnosis Age,Neoplasm Disease Stage American Joint Committee on Cancer Code,Aneuploidy Score,Buffa Hypoxia Score,Cancer Type,TCGA PanCanAtlas Cancer Type Acronym,Cancer Type Detailed,Last Communication Contact from Initial Pathologic Diagnosis Date,...,Subtype,Tumor Break Load,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site,Tissue Source Site Code,TMB (nonsynonymous),Tumor Disease Anatomic Site,Tumor Type,Winter Hypoxia Score
0,TCGA-05-4402-01,TCGA-05-4402,57,STAGE IV,31,17,Non-Small Cell Lung Cancer,LUAD,Lung Adenocarcinoma,NaN,...,LUAD,70,No,Yes,Indivumed,5,4.033333,Lung,"Lung Adenocarcinoma, Mixed Subtype",24
1,TCGA-38-6178-01,TCGA-38-6178,70,STAGE IIIA,22,-5,Non-Small Cell Lung Cancer,LUAD,Lung Adenocarcinoma,448.0,...,LUAD,188,Yes,No,UNC,38,2.233333,Lung,Lung Adenocarcinoma (NOS),4
2,TCGA-44-A4SU-01,TCGA-44-A4SU,67,STAGE IA,12,-11,Non-Small Cell Lung Cancer,LUAD,Lung Adenocarcinoma,76.0,...,LUAD,90,Yes,No,Christiana Healthcare,44,4.433333,Lung,Lung Adenocarcinoma (NOS),18
3,TCGA-49-4501-01,TCGA-49-4501,67,STAGE IB,19,5,Non-Small Cell Lung Cancer,LUAD,Lung Adenocarcinoma,1421.0,...,LUAD,182,No,Yes,Johns Hopkins,49,1.600000,Lung,Lung Adenocarcinoma (NOS),12
4,TCGA-50-6591-01,TCGA-50-6591,63,STAGE IV,28,21,Non-Small Cell Lung Cancer,LUAD,Lung Adenocarcinoma,NaN,...,LUAD,167,No,Yes,University of Pittsburgh,50,1.866667,Lung,Lung Adenocarcinoma (NOS),32

In [11]:
# Check and remove missing values
print("Shape before removing NaN:", data.shape)
print("\nMissing values per column:")
missing = data.isnull().sum()
print(missing[missing > 0])

print("\nColumn names available:")
print(data.columns.tolist())

# Remove rows with missing values in key columns
key_cols = ['Disease-specific Survival status', 'Diagnosis Age', 'Sex']
data_clean = data.dropna(subset=key_cols)
print(f"\nShape after removing NaN: {data_clean.shape}")
print(f"Rows removed: {data.shape[0] - data_clean.shape[0]}")

data_clean.head()

Shape before removing NaN: (12, 58)

Missing values per column:
Last Communication Contact from Initial Pathologic Diagnosis Date     4
Disease Free (Months)                                                 6
Disease Free Status                                                   6
Ethnicity Category                                                    1
New Neoplasm Event Post Initial Therapy Indicator                     1
Person Neoplasm Cancer Status                                         1
Primary Lymph Node Presentation Assessment                           12
Race Category                                                         1
Radiation Therapy                                                     1
dtype: int64

Column names available:
['Sample ID', 'Patient ID', 'Diagnosis Age', 'Neoplasm Disease Stage American Joint Committee on Cancer Code', 'Aneuploidy Score', 'Buffa Hypoxia Score', 'Cancer Type', 'TCGA PanCanAtlas Cancer Type Acronym', 'Cancer Type Detailed', 'Last Communication Contact from Initial Pathologic Diagnosis Date', 'Birth from Initial Pathologic Diagnosis Date', 'Last Alive Less Initial Pathologic Diagnosis Date Calculated Day Value', 'Disease Free (Months)', 'Disease Free Status', 'Months of disease-specific survival', 'Disease-specific Survival status', 'Ethnicity Category', 'Form completion date', 'Fraction Genome Altered', 'Genetic Ancestry Label', 'Neoadjuvant Therapy Type Administered Prior To Resection Text', 'ICD-10 Classification', 'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Histology Code', 'International Classification of Diseases for Oncology, Third Edition ICD-O-3 Site Code', 'Informed consent verified', 'In PanCan Pathway Analysis', 'MSI MANTIS Score', 'MSIsensor Score', 'Mutation Count', 'New Neoplasm Event Post Initial Therapy Indicator', 'Oncotree Code', 'Overall Survival (Months)', 'Overall Survival Status', 'Other Patient ID', 'Neoplasm Disease Lymph Node Stage American Joint Committee on Cancer Code', 'American Joint Committee on Cancer Tumor Stage Code', 'Person Neoplasm Cancer Status', 'Progress Free Survival (Months)', 'Progression Free Status', 'Primary Lymph Node Presentation Assessment', 'Prior Diagnosis', 'Race Category', 'Radiation Therapy', 'Ragnum Hypoxia Score', 'Number of Samples Per Patient', 'Sample Type', 'Sex', 'Somatic Status', 'Subtype', 'Tumor Break Load', 'Tissue Prospective Collection Indicator', 'Tissue Retrospective Collection Indicator', 'Tissue Source Site', 'Tissue Source Site Code', 'TMB (nonsynonymous)', 'Tumor Disease Anatomic Site', 'Tumor Type', 'Winter Hypoxia Score']

Shape after removing NaN: (12, 58)
Rows removed: 0

,Sample ID,Patient ID,Diagnosis Age,Neoplasm Disease Stage American Joint Committee on Cancer Code,Aneuploidy Score,Buffa Hypoxia Score,Cancer Type,TCGA PanCanAtlas Cancer Type Acronym,Cancer Type Detailed,Last Communication Contact from Initial Pathologic Diagnosis Date,...,Subtype,Tumor Break Load,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site,Tissue Source Site Code,TMB (nonsynonymous),Tumor Disease Anatomic Site,Tumor Type,Winter Hypoxia Score
0,TCGA-05-4402-01,TCGA-05-4402,57,STAGE IV,31,17,Non-Small Cell Lung Cancer,LUAD,Lung Adenocarcinoma,NaN,...,LUAD,70,No,Yes,Indivumed,5,4.033333,Lung,"Lung Adenocarcinoma, Mixed Subtype",24
1,TCGA-38-6178-01,TCGA-38-6178,70,STAGE IIIA,22,-5,Non-Small Cell Lung Cancer,LUAD,Lung Adenocarcinoma,448.0,...,LUAD,188,Yes,No,UNC,38,2.233333,Lung,Lung Adenocarcinoma (NOS),4
2,TCGA-44-A4SU-01,TCGA-44-A4SU,67,STAGE IA,12,-11,Non-Small Cell Lung Cancer,LUAD,Lung Adenocarcinoma,76.0,...,LUAD,90,Yes,No,Christiana Healthcare,44,4.433333,Lung,Lung Adenocarcinoma (NOS),18
3,TCGA-49-4501-01,TCGA-49-4501,67,STAGE IB,19,5,Non-Small Cell Lung Cancer,LUAD,Lung Adenocarcinoma,1421.0,...,LUAD,182,No,Yes,Johns Hopkins,49,1.600000,Lung,Lung Adenocarcinoma (NOS),12
4,TCGA-50-6591-01,TCGA-50-6591,63,STAGE IV,28,21,Non-Small Cell Lung Cancer,LUAD,Lung Adenocarcinoma,NaN,...,LUAD,167,No,Yes,University of Pittsburgh,50,1.866667,Lung,Lung Adenocarcinoma (NOS),32